### ISSUE TITLE
No network in VM

### ISSUE THREAD

**Issue by aparcar** [pktpls/openwrt-firecracker#1]
I'm I'm testing your guide but network doesn't seem to work, can you please give me a quick pointer?

```
2021-10-10T13:02:48.872465778 [anonymous-instance:main:ERROR:src/devices/src/virtio/net/device.rs:444] Failed to write to tap: Os { code: 5, kind: Other, message: "I/O error" }
```

**Comment by pktpls** [comment]
You're right, I just noticed the lack of network instructions as well :)

```sh
sudo ip tuntap add dev tap0 mode tap
sudo ip addr add 192.168.1.2/24 dev tap0
sudo ip link set dev tap0 up
sudo sysctl -w net.ipv4.conf.tap0.proxy_arp=1

sudo firecracker ... # start vm

ping 192.168.1.1
ssh root@192.168.1.1 ping 192.168.1.2
```

The `host_dev_name` setting in `vmconfig.json` is set to this interface, and Firecracker connects its remote end to the guest's virtio network interface.

This is the most basic setup I think. There's [more docs](https://github.com/firecracker-microvm/firecracker/blob/main/docs/network-setup.md) and via the VM's HTTP API more interfaces can be added.

**Comment by pktpls** [comment]
I figure one could also circumvent OpenWrt's default 192.168.1.1 by putting a custom /etc/config/network into the image. Anyway, Firecracker just plumbs the TAP and the rest is up to the user, so to speak.

**Comment by aparcar** [comment]
Would be nice if you could extend this example to have both `lan` and `wan`.

**Comment by pktpls** [comment]
That is a very good suggestion. I also want to see if software VLAN works. I'll update here when I have that.

**Comment by pktpls** [comment]
It's much nicer now! Also very convenient that we can just download a snapshot kernel now :)
